name: Github Pages Build and Deploy

on:
  push:
    branches:
      - master # Set a branch to deploy

env:
  BASE_URL: /Choices # hardcode base url to /Choices, should be set in github configs, similar to gitlab configs

permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          BASE_URL=$BASE_URL
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: dist # The folder the action should deploy.